# Generated by Django 5.1.4 on 2025-01-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('has_vegetarian', models.BooleanField(default=False)),
                ('veget_variety', models.TextField(max_length=40)),
                ('has_vegan', models.BooleanField(default=False)),
                ('vegan_variety', models.TextField(max_length=60)),
                ('notes', models.TextField()),
            ],
        ),
    ]
