# Generated by Django 5.1.4 on 2025-01-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='vegan_variety',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='veget_variety',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
