# Generated by Django 5.1.4 on 2025-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0002_alter_cardapiorestaurante_vegan_variety_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('has_vegetarian', models.BooleanField(default=False)),
                ('veget_variety', models.TextField(blank=True, max_length=40)),
                ('has_vegan', models.BooleanField(default=False)),
                ('vegan_variety', models.TextField(blank=True, max_length=60)),
                ('overview', models.TextField()),
                ('warning', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='has_vegan',
        ),
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='has_vegetarian',
        ),
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='vegan_variety',
        ),
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='veget_variety',
        ),
        migrations.AddField(
            model_name='cardapiorestaurante',
            name='menu_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardapiorestaurante',
            name='dish_collection',
            field=models.ManyToManyField(to='cardapios.prato'),
        ),
    ]
