# Generated by Django 5.1.4 on 2025-01-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0003_prato_remove_cardapiorestaurante_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='dish_collection',
        ),
        migrations.AddField(
            model_name='cardapiorestaurante',
            name='dish_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardapios.prato'),
        ),
    ]
