# Generated by Django 5.1.4 on 2025-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0004_remove_cardapiorestaurante_dish_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prato',
            name='warning',
            field=models.TextField(blank=True),
        ),
    ]
