# Generated by Django 5.1.4 on 2025-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0005_alter_prato_overview_alter_prato_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapiorestaurante',
            name='dish_collection',
        ),
        migrations.AddField(
            model_name='cardapiorestaurante',
            name='dish_collection',
            field=models.ManyToManyField(null=True, to='cardapios.prato'),
        ),
    ]
