# Generated by Django 5.1.4 on 2025-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0006_remove_cardapiorestaurante_dish_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='dish_collection',
            field=models.ManyToManyField(to='cardapios.prato'),
        ),
    ]
