# Generated by Django 5.1.4 on 2025-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0007_alter_cardapiorestaurante_dish_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='dish_collection',
            field=models.ManyToManyField(blank=True, to='cardapios.prato'),
        ),
    ]
