# Generated by Django 5.1.4 on 2025-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0008_alter_cardapiorestaurante_dish_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
