# Generated by Django 5.1.4 on 2025-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapios', '0009_alter_cardapiorestaurante_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiorestaurante',
            name='menu_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
